server:
  port: 7001
  
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
      
#服务名
spring:
  application:
    name: hello-consumer